/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.UrciuoliGonzalo.vista;

/**
 *
 * @author digit
 */
public class AplicacioUB4 extends javax.swing.JFrame {

    /**
     * Creates new form AplicacioUB4
     */
    public AplicacioUB4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        btnAfegirFitxerMultimedia = new javax.swing.JButton();
        btnEliminarImatge = new javax.swing.JButton();
        btnCrearAlbum = new javax.swing.JButton();
        btnEliminarAlbum = new javax.swing.JButton();
        btnAfegirImatgeAlbum = new javax.swing.JButton();
        btnEliminarImatgeAlbum = new javax.swing.JButton();
        btnAfegirFitxerBiblioteca = new javax.swing.JButton();
        btnPlayAlbum = new javax.swing.JButton();
        btnPlayBiblioteca = new javax.swing.JButton();
        btnPlayImBiblioteca = new javax.swing.JButton();
        btnPlatImAlbum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAfegirFitxerMultimedia.setText("Afegir Fitxer Multimedia");
        btnAfegirFitxerMultimedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFitxerMultimediaActionPerformed(evt);
            }
        });

        btnEliminarImatge.setText("jButton1");

        btnCrearAlbum.setText("jButton1");

        btnEliminarAlbum.setText("jButton1");

        btnAfegirImatgeAlbum.setText("jButton1");

        btnEliminarImatgeAlbum.setText("jButton1");

        btnAfegirFitxerBiblioteca.setText("jButton1");
        btnAfegirFitxerBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFitxerBibliotecaActionPerformed(evt);
            }
        });

        btnPlayAlbum.setText("jButton1");
        btnPlayAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAlbumActionPerformed(evt);
            }
        });

        btnPlayBiblioteca.setText("jButton1");

        btnPlayImBiblioteca.setText("jButton1");

        btnPlatImAlbum.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnAfegirFitxerMultimedia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPlayAlbum)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminarImatge)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(btnEliminarAlbum)
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(btnCrearAlbum)
                                        .addGap(49, 49, 49)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAfegirImatgeAlbum)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEliminarImatgeAlbum)
                                        .addGap(88, 88, 88)
                                        .addComponent(btnAfegirFitxerBiblioteca))))
                            .addComponent(btnPlayBiblioteca)
                            .addComponent(btnPlayImBiblioteca))
                        .addGap(51, 51, 51)
                        .addComponent(btnPlatImAlbum)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnAfegirFitxerMultimedia)
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarImatge)
                    .addComponent(btnEliminarAlbum)
                    .addComponent(btnEliminarImatgeAlbum)
                    .addComponent(btnAfegirFitxerBiblioteca))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAfegirImatgeAlbum)
                    .addComponent(btnCrearAlbum))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlayAlbum)
                    .addComponent(btnPlatImAlbum))
                .addGap(26, 26, 26)
                .addComponent(btnPlayBiblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlayImBiblioteca)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfegirFitxerMultimediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFitxerMultimediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAfegirFitxerMultimediaActionPerformed

    private void btnAfegirFitxerBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFitxerBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAfegirFitxerBibliotecaActionPerformed

    private void btnPlayAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacioUB4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirFitxerBiblioteca;
    private javax.swing.JButton btnAfegirFitxerMultimedia;
    private javax.swing.JButton btnAfegirImatgeAlbum;
    private javax.swing.JButton btnCrearAlbum;
    private javax.swing.JButton btnEliminarAlbum;
    private javax.swing.JButton btnEliminarImatge;
    private javax.swing.JButton btnEliminarImatgeAlbum;
    private javax.swing.JButton btnPlatImAlbum;
    private javax.swing.JButton btnPlayAlbum;
    private javax.swing.JButton btnPlayBiblioteca;
    private javax.swing.JButton btnPlayImBiblioteca;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
